# Generated by Django 5.2.6 on 2025-12-28 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_groupchat_groupchatmessage_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
