# Generated by Django 5.2.6 on 2025-10-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='spotlight_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_spotlight_background/'),
        ),
    ]
