# Generated by Django 5.2.6 on 2025-11-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phonepe_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
