# Generated by Django 5.2.6 on 2025-12-02 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_content_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresponse',
            name='instructor_feedback',
        ),
        migrations.RemoveField(
            model_name='studentresponse',
            name='marks_awarded',
        ),
        migrations.RemoveField(
            model_name='studentresponse',
            name='text_response',
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.answer'),
        ),
    ]
