# Generated by Django 5.2.6 on 2026-02-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='subject',
            field=models.CharField(max_length=600),
        ),
    ]
