# Generated by Django 5.2.6 on 2026-02-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_alter_support_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_template',
            field=models.ImageField(blank=True, null=True, upload_to='certificate_templates/'),
        ),
    ]
