# Generated by Django 5.2.6 on 2026-01-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_remove_communitypost_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='polloption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='poll_images/'),
        ),
    ]
