# Generated by Django 5.2.6 on 2025-11-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_qualification_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qualification',
            field=models.CharField(max_length=50),
        ),
    ]
