# Generated by Django 5.2.6 on 2025-11-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qualification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
