# Generated by Django 5.2.6 on 2026-01-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_is_email_verified_onetimepassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorapplication',
            name='certificate_file',
        ),
        migrations.RemoveField(
            model_name='instructorapplication',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='instructorapplication',
            name='social_links',
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='instructor_cvs/'),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='dob',
            field=models.DateField(default='2004-09-18', help_text='Date of Birth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='domain_expertise',
            field=models.CharField(default=' ', help_text='e.g., Web Development, Data Science', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructorapplication',
            name='bio',
            field=models.TextField(help_text='Tell us about yourself'),
        ),
    ]
