# Generated by Django 5.2.6 on 2026-02-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_instructorapplication_certificate_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/user.svg', upload_to='profile_pics/'),
        ),
    ]
