# Generated by Django 5.2.6 on 2026-02-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorapplication',
            name='linkedin_profile',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
